spring.application.name=Ecommerce

# In our application we are useing MySQl database

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
# Username of the database
spring.datasource.username=YOUR_DATABASE_USERNAME
# Password of the database
spring.datasource.password=YOUR_DATABASE_PASSWORD


# JPA configuration
# To update the table (It does't delete the table every time)
spring.jpa.hibernate.ddl-auto=update
# It shows the sql queries on terminal
spring.jpa.show-sql=true


